SELECT HP.PARTY_ID AS VENDOR_ID,
       HP.PARTY_NAME,
       (SELECT name from HR_ORGANIZATION_UNITS HOU where HOU.ORGANIZATION_ID = :P_UNIT_NAME) UNIT,
       (SELECT PARTY_NAME FROM HZ_PARTIES WHERE PARTY_ID = :P_PARTY_ID) SUPPLIER,
       NVL (DEBIT_AMOUNT, 0) DEBIT_AMOUNT,
       NVL (CREDIT_AMOUNT, 0) CREDIT_AMOUNT,
       (NVL (CREDIT_AMOUNT, 0) - NVL (DEBIT_AMOUNT, 0)) BALANCE
  FROM HZ_PARTIES HP
       LEFT OUTER JOIN 
       (SELECT PARTY_ID,SUM (NVL (CH.AMOUNT, 0)) DEBIT_AMOUNT
            FROM AP_CHECKS_ALL CH JOIN HR_ORGANIZATION_UNITS HOU
            ON CH.ORG_ID = HOU.ORGANIZATION_ID
           WHERE CH.ORG_ID = NVL(:P_UNIT_NAME,CH.ORG_ID)
           GROUP BY PARTY_ID) DR
          ON HP.PARTY_ID = DR.PARTY_ID
       LEFT OUTER JOIN
       (  SELECT VENDOR_ID, PARTY_ID, SUM (NVL(APA.INVOICE_AMOUNT,0)) AS CREDIT_AMOUNT
            FROM AP_INVOICES_ALL APA JOIN HR_ORGANIZATION_UNITS HOU
            ON APA.ORG_ID = HOU.ORGANIZATION_ID
           WHERE INVOICE_TYPE_LOOKUP_CODE = 'STANDARD'
           AND APA.ORG_ID = NVL(:P_UNIT_NAME,APA.ORG_ID)  
        GROUP BY PARTY_ID, VENDOR_ID) CR
            ON HP.PARTY_ID = CR.PARTY_ID
 WHERE HP.PARTY_ID = NVL(:P_PARTY_ID,HP.PARTY_ID)
 order by HP.PARTY_NAME