/*
Supplier Voucher Data Model For Fusion Application
Created By: Showkat Hossain
Create Date: 25-Dec-2020
Update Date: 20-Jun-2021
*/
SELECT  BU,
        COMPANY_NAME,
        PARTY_SITE_NAME,
        ENTITY_ID,
        VOUCHER_NO,
        INVOICE_TYPE_LOOKUP_CODE,
        GL_DATE,
        INVOICE_ID,
        INVOICE_NUM,
        INVOICE_AMOUNT,
        DESCRIPTION,
        EXCHANGE_RATE,
        ACC_CURR,
        INVOICE_CURRENCY_CODE,
        REMIT_TO_SUPPLIER_NAME,
        VENDOR_NAME,
        NTN_NUMBER,
        NIC_NUMBER,
        CREATED_BY,
        ACCOUNT_CODE,                                      
        LINE_DESC,
        PARTICULAR,
        CREDIT,
        DEBIT,
        CALC_CREDIT,
        CALC_DEBIT,
        PAYMENT_METHOD_CODE,
        INVOICE_DATE,
        PARTY_ID,
        PO_NUM,
        RECEIPT_NUM,
        ATTRIBUTE13,
        ORG_ID,
        (INVOICE_AMOUNT - nvl(AMOUNT_PAID,0) - NVL(TOTAL_TAX_AMOUNT,0)) AMOUNT_PAID,
        TERMS_ID,
        abs((SELECT SUM(NVL(aila1.AMOUNT,0))
          FROM AP_INVOICE_LINES_ALL AILA1
         WHERE INVOICE_ID = TAB1.INVOICE_ID
         AND AILA1.PREPAY_INVOICE_ID is not null
         and LINE_TYPE_LOOKUP_CODE='PREPAY'))  PRE_PAYMENT
FROM
(SELECT KFV.SEGMENT1 BU,
       (SELECT HOU.NAME
          FROM HR_OPERATING_UNITS HOU
         WHERE HOU.ORGANIZATION_ID = AIA.ORG_ID AND ROWNUM = 1)
          COMPANY_NAME,
       APS.VENDOR_SITE_CODE PARTY_SITE_NAME,
       AIA.LEGAL_ENTITY_ID ENTITY_ID,
       AIA.DOC_SEQUENCE_VALUE VOUCHER_NO,
       (SELECT LOOKUP_CODE
          FROM FND_LOOKUP_VALUES_VL
         WHERE     LOOKUP_TYPE = 'INVOICE TYPE'
               AND LOOKUP_CODE = AIA.INVOICE_TYPE_LOOKUP_CODE)
          INVOICE_TYPE_LOOKUP_CODE,
       TO_CHAR (AIA.GL_DATE, 'DD-MM-YYYY') GL_DATE,
       AIA.INVOICE_ID,
       AIA.INVOICE_NUM,
       AIA.INVOICE_AMOUNT,
       AIA.DESCRIPTION,
       NVL (AIA.EXCHANGE_RATE, 1) EXCHANGE_RATE,
       DECODE (AIA.ORG_ID, 345, 'HKD', 'BDT') ACC_CURR,
       AIA.INVOICE_CURRENCY_CODE,
       AIA.REMIT_TO_SUPPLIER_NAME,
       HZP.PARTY_NAME VENDOR_NAME,
       HZP.ATTRIBUTE1 NTN_NUMBER,
       HZP.ATTRIBUTE2 NIC_NUMBER,
       FU.USERNAME CREATED_BY,
       (SELECT fnd_flex_ext.get_segs ('GL','GL#',KFV.CHART_OF_ACCOUNTS_ID,KFV.CODE_COMBINATION_ID)FROM DUAL) ACCOUNT_CODE,                                      --Need to use API
       FFVV.DESCRIPTION LINE_DESC,
       AILA.DESCRIPTION PARTICULAR,
       NULL CREDIT,
       AIDA.AMOUNT DEBIT,
       NULL CALC_CREDIT,
       AIDA.AMOUNT * NVL (AIA.EXCHANGE_RATE, 1) CALC_DEBIT,
       (SELECT IPMT.DESCRIPTION
          FROM IBY_PAYMENT_METHODS_TL IPMT
         WHERE     IPMT.PAYMENT_METHOD_CODE = AIA.PAYMENT_METHOD_CODE
               AND ROWNUM = 1)
          PAYMENT_METHOD_CODE,
       TO_CHAR (aia.INVOICE_DATE,'DD-MM-YYYY') INVOICE_DATE,
       (SELECT APS.SEGMENT1
          FROM POZ_SUPPLIERS APS
         WHERE APS.VENDOR_ID = AIA.VENDOR_ID)
          PARTY_ID,
       (  SELECT LISTAGG (PO, '-') WITHIN GROUP (ORDER BY CREATION_DATE)
                    AS DESC_GH
            FROM (  SELECT PHA.SEGMENT1 PO,
                           AILA.INVOICE_ID INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE) CREATION_DATE
                      FROM AP_INVOICE_LINES_ALL AILA, PO_HEADERS_ALL PHA
                     WHERE AILA.PO_HEADER_ID = PHA.PO_HEADER_ID
                  GROUP BY AILA.INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE),
                           PHA.SEGMENT1)
           WHERE INVOICE_ID = AIA.INVOICE_ID
        GROUP BY INVOICE_ID)
          PO_NUM,
       ( SELECT LISTAGG (PO, '-') WITHIN GROUP (ORDER BY CREATION_DATE)
                    AS DESC_GH
            FROM (  SELECT RSH.RECEIPT_NUM PO,
                           AILA.INVOICE_ID INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE) CREATION_DATE
                      FROM RCV_TRANSACTIONS RT,
                           RCV_SHIPMENT_HEADERS RSH,
                           AP_INVOICE_LINES_ALL AILA
                     WHERE     AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
                           AND RT.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
                  GROUP BY AILA.INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE),
                           RSH.RECEIPT_NUM)
           WHERE INVOICE_ID = AIA.INVOICE_ID
        GROUP BY INVOICE_ID)
          RECEIPT_NUM,
       AIA.ATTRIBUTE13,
       AIA.ORG_ID,
       AIA.AMOUNT_PAID,
       NVL(AIA.TOTAL_TAX_AMOUNT,0) TOTAL_TAX_AMOUNT,
       (SELECT AT.NAME
          FROM AP_TERMS AT
         WHERE AT.TERM_ID = AIA.TERMS_ID AND ROWNUM = 1)
          TERMS_ID
  FROM AP_INVOICES_ALL AIA,
       AP_INVOICE_LINES_ALL AILA,
       AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
       PER_USERS FU,
       HZ_PARTIES HZP,
       AP_POZ_SITE_AND_ASSIGNMENT_V APS,
       GL_CODE_COMBINATIONS KFV,
       FND_FLEX_VALUES_VL FFVV
 WHERE     1 = 1
       AND AIA.INVOICE_ID = AILA.INVOICE_ID(+)
       AND AIA.INVOICE_ID = AIDA.INVOICE_ID(+)
       AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
       AND AILA.INVOICE_ID = AIDA.INVOICE_ID
       AND AIA.CREATED_BY = FU.USERNAME(+)
       AND AIA.PARTY_ID = HZP.PARTY_ID(+)
       AND AIA.VENDOR_SITE_ID = APS.VENDOR_SITE_ID(+)
       AND AIDA.AMOUNT <> 0
       AND AIDA.LINE_TYPE_LOOKUP_CODE NOT IN ('PREPAY','AWT')
       AND AIDA.DIST_CODE_COMBINATION_ID = KFV.CODE_COMBINATION_ID
       AND FFVV.FLEX_VALUE = KFV.SEGMENT4
       AND FFVV.FLEX_VALUE_SET_ID = 55005
       AND AIA.ORG_ID = NVL (:P_ORG_ID, AIA.ORG_ID)
       and HZP.PARTY_ID = NVL(:P_SUPPLIER_ID,HZP.PARTY_ID)
       and AIA.INVOICE_AMOUNT BETWEEN NVL(:P_AMOUNT_FROM,AIA.INVOICE_AMOUNT) AND NVL(:P_AMOUNT_TO,AIA.INVOICE_AMOUNT)
       and aia.INVOICE_DATE BETWEEN NVL(:P_invoice_date_From,aia.INVOICE_DATE) and NVL(:P_invoice_date_to,aia.INVOICE_DATE)
       AND AIA.INVOICE_NUM = NVL(:P_INVOUCE_NUMBER,AIA.INVOICE_NUM) 
       AND NVL(AIA.DOC_SEQUENCE_VALUE,00) BETWEEN NVL (:P_VOUCHER_NUMBER_FROM,NVL(AIA.DOC_SEQUENCE_VALUE,00)) AND NVL (:P_VOUCHER_NUMBER_TO,NVL(AIA.DOC_SEQUENCE_VALUE,00))
UNION ALL
SELECT KFV.SEGMENT1 BU,
       (SELECT HOU.NAME
          FROM HR_OPERATING_UNITS HOU
         WHERE HOU.ORGANIZATION_ID = AIA.ORG_ID AND ROWNUM = 1)
          COMPANY_NAME,
       APS.VENDOR_SITE_CODE PARTY_SITE_NAME,
       AIA.LEGAL_ENTITY_ID ENTITY_ID,
       AIA.DOC_SEQUENCE_VALUE VOUCHER_NO,
       (SELECT LOOKUP_CODE
          FROM FND_LOOKUP_VALUES_VL
         WHERE     LOOKUP_TYPE = 'INVOICE TYPE'
               AND LOOKUP_CODE = AIA.INVOICE_TYPE_LOOKUP_CODE)
          INVOICE_TYPE_LOOKUP_CODE,
       TO_CHAR (AIA.GL_DATE, 'DD-MM-YYYY') GL_DATE,
       AIA.INVOICE_ID,
       AIA.INVOICE_NUM,
       AIA.INVOICE_AMOUNT,
       AIA.DESCRIPTION,
       NVL (AIA.EXCHANGE_RATE, 1) EXCHANGE_RATE,
       DECODE (AIA.ORG_ID, 345, 'HKD', 'BDT') ACC_CURR,
       AIA.INVOICE_CURRENCY_CODE,
       AIA.REMIT_TO_SUPPLIER_NAME,
       HZP.PARTY_NAME VENDOR_NAME,
       HZP.ATTRIBUTE1 NTN_NUMBER,
       HZP.ATTRIBUTE2 NIC_NUMBER,
       FU.USERNAME CREATED_BY,
       (SELECT fnd_flex_ext.get_segs ('GL','GL#',KFV.CHART_OF_ACCOUNTS_ID,KFV.CODE_COMBINATION_ID)FROM DUAL) ACCOUNT_CODE,                                      --Need to use API
       FFVV.DESCRIPTION LINE_DESC,
       AIA.DESCRIPTION PARTICULAR,
       AIA.INVOICE_AMOUNT CREDIT,
       NULL DEBIT,
       AIA.INVOICE_AMOUNT * NVL (AIA.EXCHANGE_RATE, 1) CALC_CREDIT,
       NULL CALC_DEBIT,
       (SELECT IPMT.DESCRIPTION
          FROM IBY_PAYMENT_METHODS_TL IPMT
         WHERE     IPMT.PAYMENT_METHOD_CODE = AIA.PAYMENT_METHOD_CODE
               AND ROWNUM = 1)
          PAYMENT_METHOD_CODE,
       TO_CHAR (aia.INVOICE_DATE,'DD-MM-YYYY') INVOICE_DATE,
       (SELECT APS.SEGMENT1
          FROM POZ_SUPPLIERS APS
         WHERE APS.VENDOR_ID = AIA.VENDOR_ID)
          PARTY_ID,
       (  SELECT LISTAGG (PO, '-') WITHIN GROUP (ORDER BY CREATION_DATE)
                    AS DESC_GH
            FROM (  SELECT PHA.SEGMENT1 PO,
                           AILA.INVOICE_ID INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE) CREATION_DATE
                      FROM AP_INVOICE_LINES_ALL AILA, PO_HEADERS_ALL PHA
                     WHERE AILA.PO_HEADER_ID = PHA.PO_HEADER_ID
                  GROUP BY AILA.INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE),
                           PHA.SEGMENT1)
           WHERE INVOICE_ID = AIA.INVOICE_ID
        GROUP BY INVOICE_ID)
          PO_NUM,
       (  SELECT LISTAGG (PO, '-') WITHIN GROUP (ORDER BY CREATION_DATE)
                    AS DESC_GH
            FROM (  SELECT RSH.RECEIPT_NUM PO,
                           AILA.INVOICE_ID INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE) CREATION_DATE
                      FROM RCV_TRANSACTIONS RT,
                           RCV_SHIPMENT_HEADERS RSH,
                           AP_INVOICE_LINES_ALL AILA
                     WHERE     AILA.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
                           AND RT.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
                  GROUP BY AILA.INVOICE_ID,
                           TRUNC (AILA.CREATION_DATE),
                           RSH.RECEIPT_NUM)
           WHERE INVOICE_ID = AIA.INVOICE_ID
        GROUP BY INVOICE_ID)
          RECEIPT_NUM,
       AIA.ATTRIBUTE13,
       AIA.ORG_ID,
       AIA.AMOUNT_PAID,
       NVL(AIA.TOTAL_TAX_AMOUNT,0) TOTAL_TAX_AMOUNT,
       (SELECT AT.NAME
          FROM AP_TERMS AT
         WHERE AT.TERM_ID = AIA.TERMS_ID AND ROWNUM = 1)
          TERMS_ID
  FROM AP_INVOICES_ALL AIA,
       --AP_INVOICE_DISTRIBUTIONS_ALL AIDA,
       GL_CODE_COMBINATIONS KFV,
       PER_USERS FU,
       HZ_PARTIES HZP,
       AP_POZ_SITE_AND_ASSIGNMENT_V APS,
       FND_FLEX_VALUES_VL FFVV
 WHERE     1 = 1
       AND AIA.ACCTS_PAY_CODE_COMBINATION_ID = KFV.CODE_COMBINATION_ID
       AND AIA.CREATED_BY = FU.USERNAME(+)
       AND AIA.PARTY_ID = HZP.PARTY_ID(+)
--       AND AIA.INVOICE_ID = AIDA.INVOICE_ID(+)
       AND AIA.VENDOR_SITE_ID = APS.VENDOR_SITE_ID(+)
       AND FFVV.FLEX_VALUE = KFV.SEGMENT4
       AND FFVV.FLEX_VALUE_SET_ID = 55005
       --AND AIDA.LINE_TYPE_LOOKUP_CODE <> 'PREPAY'
       AND AIA.ORG_ID = NVL (:P_ORG_ID, AIA.ORG_ID)
       and HZP.PARTY_ID = NVL(:P_SUPPLIER_ID,HZP.PARTY_ID)
       and AIA.INVOICE_AMOUNT BETWEEN NVL(:P_AMOUNT_FROM,AIA.INVOICE_AMOUNT) AND NVL(:P_AMOUNT_TO,AIA.INVOICE_AMOUNT)
       and aia.INVOICE_DATE BETWEEN NVL(:P_invoice_date_From,aia.INVOICE_DATE) and NVL(:P_invoice_date_to,aia.INVOICE_DATE)
       AND AIA.INVOICE_NUM = NVL(:P_INVOUCE_NUMBER,AIA.INVOICE_NUM) 
       AND NVL(AIA.DOC_SEQUENCE_VALUE,00) BETWEEN NVL (:P_VOUCHER_NUMBER_FROM,NVL(AIA.DOC_SEQUENCE_VALUE,00)) AND NVL (:P_VOUCHER_NUMBER_TO,NVL(AIA.DOC_SEQUENCE_VALUE,00))
)TAB1
ORDER BY DEBIT NULLS LAST, CREDIT NULLS LAST